# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Computer Networks, 1DV701
email: jherrlin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  John Herrlin
  BS CS student at LNU university in Vaxjo, Sweden.
baseurl: "/Computer-Networks-1DV701" # the subpath of your site, e.g. /blog
url: "http://jherrlin.github.io/Computer-Networks-1DV701/" # the base hostname & protocol for your site
twitter_username: jherrlin
github_username:  jherrlin

# Build settings
markdown: kramdown
